//@version=1
// __TITLE__
// FX Replay (FXR Script) indicator, generated by: python -m confluence.cli fxr-script __SID__
//
// Put it on an NQ __TF__-minute chart. It marks every setup, simulates the trade the
// backtest takes (entry, stop, exit) and keeps a running tally in R and dollars.
// Take the marked trades with FX Replay's order tools to journal them.
//
// Backtest, Sep 2018 - Sep 2026 on the Nasdaq-100 CFD: __STATS__
// The script sees bars, not the 1-minute path inside them, so a few exits can differ.
// If anything fails, a red line labelled "SCRIPT ERROR" marks the bar where it happened.

// ------------------------------------------------------------------ strategy constants
var CFG = {
  sid: '__SID__',
  tf: __TF__,                // chart timeframe the rules were tested on (minutes)
  signal: '__SIGNAL__',      // setup detector: 'swingEngulf' or 'ifvgRetest'
  entry: '__ENTRY__',        // 'market' = next bar open; 'stop' = 1 tick beyond the signal bar, valid 3 bars
  stopAtr: __STOPATR__,      // initial stop = stopAtr x ATR(14) of the signal bar from the entry
  trail: __TRAIL__,          // after +1R, trail 2 x ATR(14) behind the best price at each bar close
  sesFrom: __SESFROM__,      // the signal bar must CLOSE between these New York times (minutes after midnight)
  sesTo: __SESTO__,
  flatAt: __FLAT__,          // flat at this New York time
  maxPerDay: 4,
  warmup: 300,               // no setups in the first 300 bars while ATR, swings and averages settle
  atrLen: 14,
  swingAtr: 3.0,             // a swing high/low is confirmed after a 3 x ATR reversal
  minStopAtr: 0.3,           // stops never tighter than 0.3 ATR
  minStopCosts: 4.0          // ... or 4 round-trip costs
};

init = () => {
  indicator({ onMainPanel: true, format: 'inherit' });
  input.float('Risk per trade ($)', 500, 'riskUsd', 10, 10000, 10);
  input.float('Point value per contract ($)', 2, 'pointValue', 0.1, 100, 0.1);
  input.float('Round-trip cost (points)', 1.11, 'costPts', 0, 20, 0.01);
  input.float('Tick size', 0.25, 'tick', 0.0001, 10, 0.0001);
  input.bool('Take shorts', true, 'shorts');
  input.bool('Draw trades', true, 'draw');
  input.int('Trades kept on chart', 100, 'keep', 1, 2000, 1);
};

// ------------------------------------------------------------------ settings (defaults until inputs arrive)
var IN = { riskUsd: 500, pointValue: 2, costPts: 1.11, tick: 0.25, shorts: true, draw: true, keep: 100 };
var readInputs = function (inputs) {
  if (!inputs) return;
  if (typeof inputs.riskUsd === 'number') IN.riskUsd = inputs.riskUsd;
  if (typeof inputs.pointValue === 'number') IN.pointValue = inputs.pointValue;
  if (typeof inputs.costPts === 'number') IN.costPts = inputs.costPts;
  if (typeof inputs.tick === 'number') IN.tick = inputs.tick;
  if (typeof inputs.shorts === 'boolean') IN.shorts = inputs.shorts;
  if (typeof inputs.draw === 'boolean') IN.draw = inputs.draw;
  if (typeof inputs.keep === 'number') IN.keep = inputs.keep;
};

// ------------------------------------------------------------------ New York clock
var DAY_MS = 86400000;
var toMs = function (t) { return t < 1e12 ? t * 1000 : t; };
var nthSunday = function (y, m, n) {           // UTC ms of the n-th Sunday of month m (0-based)
  var first = new Date(Date.UTC(y, m, 1)).getUTCDay();
  return Date.UTC(y, m, 1 + ((7 - first) % 7) + 7 * (n - 1));
};
var nyOffsetHours = function (ms) {            // US daylight time: 2nd Sun Mar 07:00 UTC to 1st Sun Nov 06:00 UTC
  var y = new Date(ms).getUTCFullYear();
  var a = nthSunday(y, 2, 2) + 7 * 3600000;
  var b = nthSunday(y, 10, 1) + 6 * 3600000;
  return (ms >= a && ms < b) ? -4 : -5;
};
// The trading day rolls at 18:00 New York; "tdm" = minutes since 18:00.
var tradingDay = function (ms) { return Math.floor((ms + nyOffsetHours(ms) * 3600000 + 6 * 3600000) / DAY_MS); };
var tradingMinute = function (ms) {
  var local = ms + nyOffsetHours(ms) * 3600000 + 6 * 3600000;
  return Math.floor((((local % DAY_MS) + DAY_MS) % DAY_MS) / 60000);
};
var tdmOf = function (minutesAfterMidnight) { return (((minutesAfterMidnight - 18 * 60) % 1440) + 1440) % 1440; };

// ------------------------------------------------------------------ state
var BT = new Array(0), BO = new Array(0), BH = new Array(0), BL = new Array(0), BC = new Array(0);
var BDAY = new Array(0), BTDMO = new Array(0), BTDMC = new Array(0);
var TRUE_RANGE = new Array(0), ATR = new Array(0), ATR_SUM100 = new Array(0);
var PIVOTS = new Array(0);                     // {p, type: 1 swing high / -1 swing low}
var zz = { d: 0, hi: -1e300, hiI: 0, lo: 1e300, loI: 0 };
var bearGap = { ok: false, top: 0, bot: 0, j: -1 };
var bullGap = { ok: false, top: 0, bot: 0, j: -1 };
var order = { open: false, kind: '', dir: 0, px: 0, sig: -1, day: -1, atr: 0, alive: false, until: -1 };
var pos = { open: false, dir: 0, entry: 0, stop: 0, stop0: 0, risk: 0, best: 0, fill: -1, sig: -1, day: -1, trailing: false, contracts: 0 };
var curDay = -1, dayCount = 0, lastSeen = -1;
var trades = new Array(0);
var drawn = new Array(0);                      // drawing ids per trade, oldest first
var totalR = 0;
var errorShown = false;

var resetState = function () {
  BT = new Array(0); BO = new Array(0); BH = new Array(0); BL = new Array(0); BC = new Array(0);
  BDAY = new Array(0); BTDMO = new Array(0); BTDMC = new Array(0);
  TRUE_RANGE = new Array(0); ATR = new Array(0); ATR_SUM100 = new Array(0); PIVOTS = new Array(0);
  zz = { d: 0, hi: -1e300, hiI: 0, lo: 1e300, loI: 0 };
  bearGap = { ok: false, top: 0, bot: 0, j: -1 };
  bullGap = { ok: false, top: 0, bot: 0, j: -1 };
  order.open = false; pos.open = false;
  curDay = -1; dayCount = 0;
  trades = new Array(0); totalR = 0;
};

// ------------------------------------------------------------------ indicators
var updateIndicators = function (k) {
  var h = BH[k], l = BL[k];
  var tr = h - l;
  if (k > 0) tr = Math.max(h - l, Math.abs(h - BC[k - 1]), Math.abs(l - BC[k - 1]));
  TRUE_RANGE[k] = tr;
  var n = CFG.atrLen;
  if (k < n - 1) ATR[k] = NaN;
  else if (k === n - 1) {
    var s = 0;
    for (var j = 0; j < n; j++) s += TRUE_RANGE[j];
    ATR[k] = s / n;
  } else ATR[k] = (ATR[k - 1] * (n - 1) + tr) / n;
  // running sum of ATR (NaN counted as 0) for the 100-bar average
  var az = isNaN(ATR[k]) ? 0 : ATR[k];
  ATR_SUM100[k] = (k > 0 ? ATR_SUM100[k - 1] : 0) + az;
  // zigzag swings, confirmed on the bar where the reversal happens
  var a = ATR[k];
  if (a > 0) {
    if (h > zz.hi) { zz.hi = h; zz.hiI = k; }
    if (l < zz.lo) { zz.lo = l; zz.loI = k; }
    if (zz.d >= 0 && zz.hi - l >= CFG.swingAtr * a && (zz.d === 1 || zz.hiI > zz.loI)) {
      PIVOTS.push({ p: zz.hi, type: 1 });
      zz.d = -1; zz.lo = l; zz.loI = k;
    } else if (zz.d <= 0 && h - zz.lo >= CFG.swingAtr * a && (zz.d === -1 || zz.loI > zz.hiI)) {
      PIVOTS.push({ p: zz.lo, type: -1 });
      zz.d = 1; zz.hi = h; zz.hiI = k;
    }
  }
};
var atrAverage100 = function (k) {
  if (k < 99) return NaN;
  return (ATR_SUM100[k] - (k >= 100 ? ATR_SUM100[k - 100] : 0)) / 100;
};

// ------------------------------------------------------------------ setups; each returns {up, dn}
// 36-221: a recent swing low retested as support + bullish engulfing + ATR below its 100-bar average
var swingEngulf = function (k) {
  var out = { up: false, dn: false };
  if (k < 1) return out;
  var o = BO[k], h = BH[k], l = BL[k], c = BC[k], o1 = BO[k - 1], c1 = BC[k - 1], a = ATR[k];
  var calm = ATR[k] < atrAverage100(k);
  var engUp = c1 < o1 && c > o && c >= o1 && o <= c1;
  var engDn = c1 > o1 && c < o && c <= o1 && o >= c1;
  var sup = false, res = false, nl = 0, nh = 0;
  if (PIVOTS.length >= 2) {
    for (var j = PIVOTS.length - 1; j >= 0 && (nl < 4 || nh < 4); j--) {
      var pv = PIVOTS[j];
      if (pv.type === -1 && nl < 4) {
        nl++;
        if (pv.p < c && Math.abs(l - pv.p) <= 0.25 * a && c > pv.p) sup = true;
      } else if (pv.type === 1 && nh < 4) {
        nh++;
        if (pv.p > c && Math.abs(h - pv.p) <= 0.25 * a && c < pv.p) res = true;
      }
    }
  }
  out.up = sup && engUp && calm;
  out.dn = res && engDn && calm;
  return out;
};
// 21-155: the bar trades into a fair-value gap from the last 20 bars and closes back through it,
// closes beyond the prior bar's extreme, and closes in the outer 30% of its range
var ifvgRetest = function (k) {
  var out = { up: false, dn: false };
  if (k < 2) return out;
  var o = BO[k], h = BH[k], l = BL[k], c = BC[k];
  var r = Math.max(h - l, 1e-12);
  var bearOk = bearGap.ok && bearGap.j <= k - 1 && (k - 1) - bearGap.j <= 20;
  var bullOk = bullGap.ok && bullGap.j <= k - 1 && (k - 1) - bullGap.j <= 20;
  out.up = bearOk && l <= bearGap.top && c > bearGap.bot && c > bearGap.top && c > BH[k - 1] && c > o && (c - l) >= 0.7 * r;
  out.dn = bullOk && h >= bullGap.bot && c < bullGap.top && c < bullGap.bot && c < BL[k - 1] && c < o && (h - c) >= 0.7 * r;
  // remember gaps formed on this bar (usable from the next bar)
  var a = ATR[k], h2 = BH[k - 2], l2 = BL[k - 2];
  if (h < l2 && (l2 - h) > 0.1 * a) bearGap = { ok: true, top: l2, bot: h, j: k };
  if (l > h2 && (l - h2) > 0.1 * a) bullGap = { ok: true, top: l, bot: h2, j: k };
  return out;
};
var setupAt = function (k) {
  if (CFG.signal === 'swingEngulf') return swingEngulf(k);
  return ifvgRetest(k);
};

// ------------------------------------------------------------------ drawing (never lets a drawing error stop the logic)
// Marker series (plot.shapes) take colour strings; drawing tools (trendLine, text) take FX Replay
// colour values, so those are built with color.rgba(...) when drawing.
var GREEN = 'rgba(38, 166, 91, 0.95)', RED = 'rgba(235, 64, 52, 0.95)';
var winColor = function () { return color.rgba(38, 166, 91, 0.95); };
var lossColor = function () { return color.rgba(235, 64, 52, 0.95); };
var stopColor = function () { return color.rgba(235, 64, 52, 0.6); };
var fmt = function (x, d) { return (x >= 0 ? '+' : '-') + Math.abs(x).toFixed(d); };
var money = function (x) {
  var s = String(Math.round(Math.abs(x)));
  var out = '';
  while (s.length > 3) { out = ',' + s.slice(-3) + out; s = s.slice(0, -3); }
  return (x < 0 ? '-$' : '$') + s + out;
};
var tryDraw = function (fn) {
  try { return fn(); } catch (e) { showError('drawing: ' + String(e)); return ''; }
};
// Marks the bar where something failed with a red vertical line labelled with the message.
var showError = function (msg) {
  if (errorShown) return;
  errorShown = true;
  try {
    var k = BT.length - 1;
    if (k >= 0) trendLine(newPoint(BT[k], BH[k]), newPoint(BT[k], BL[k]),
      { linecolor: lossColor(), linewidth: 3, showLabel: true }, CFG.sid + ' SCRIPT ERROR: ' + msg);
  } catch (e2) { /* nothing else to do */ }
};
var drawTrade = function (tr) {
  if (!IN.draw) return;
  var ids = new Array(0);
  ids.push(tryDraw(function () {
    return trendLine(newPoint(tr.t0, tr.entry), newPoint(tr.t1, tr.exit),
      { linecolor: tr.r > 0 ? winColor() : lossColor(), linewidth: 2, showLabel: true },
      CFG.sid + ' #' + trades.length + ' ' + (tr.dir > 0 ? 'long' : 'short') + ' ' + fmt(tr.r, 2) + 'R | total ' +
      fmt(totalR, 1) + 'R = ' + money(totalR * IN.riskUsd));
  }));
  ids.push(tryDraw(function () {
    return trendLine(newPoint(tr.t0, tr.stop), newPoint(tr.t1, tr.stop), { linecolor: stopColor(), linewidth: 1, linestyle: 2 });
  }));
  drawn.push(ids);
  while (drawn.length > IN.keep) {
    var old = drawn.shift();
    if (!old) break;
    for (var i = 0; i < old.length; i++) removeDrawing(old[i]);
  }
};
var removeDrawing = function (id) {
  if (!id) return;
  try { deleteDrawingById(id); } catch (e) { showError('delete: ' + String(e)); }
};
// Series markers: one fixed style per series (the text, colour and shape never change).
var markSetup = function (dir, price) {
  if (!IN.draw) return;
  tryDraw(function () {
    if (dir > 0) plot.shapes('Long setup', price, 'setup', GREEN, '#FFFFFF', 'shape_triangle_up', 'BelowBar', 'tiny', -1, 0, 'long_setup');
    else plot.shapes('Short setup', price, 'setup', RED, '#FFFFFF', 'shape_triangle_down', 'AboveBar', 'tiny', -1, 0, 'short_setup');
  });
};
var markEntry = function (dir, price) {
  if (!IN.draw) return;
  tryDraw(function () {
    if (dir > 0) plot.shapes('Buy', price, 'BUY', GREEN, '#FFFFFF', 'shape_arrow_up', 'BelowBar', 'small', -1, 0, 'buy_fill');
    else plot.shapes('Sell', price, 'SELL', RED, '#FFFFFF', 'shape_arrow_down', 'AboveBar', 'small', -1, 0, 'sell_fill');
  });
};

// ------------------------------------------------------------------ the trade simulation
var exitTdm = function () { return tdmOf(CFG.flatAt); };
var closeTrade = function (xp, k, why) {
  var r = ((xp - pos.entry) * pos.dir) / pos.risk - IN.costPts / pos.risk;
  var tr = { dir: pos.dir, t0: BT[pos.fill], entry: pos.entry, stop: pos.stop0, t1: BT[k], exit: xp, r: r, why: why,
             sig: BT[pos.sig], day: pos.day, contracts: pos.contracts };
  trades.push(tr);
  totalR += r;
  pos.open = false;
  drawTrade(tr);
};
var openTrade = function (k, entry) {
  var a = order.atr, dir = order.dir;
  var stop = entry - dir * CFG.stopAtr * a;
  var risk = (entry - stop) * dir;
  var floor = Math.max(CFG.minStopAtr * a, CFG.minStopCosts * IN.costPts);
  if (!(risk >= floor)) { risk = floor; stop = entry - dir * risk; }
  pos.open = true; pos.dir = dir; pos.entry = entry; pos.stop = stop; pos.stop0 = stop; pos.risk = risk; pos.best = entry;
  pos.fill = k; pos.sig = order.sig; pos.day = order.day; pos.trailing = false;
  pos.contracts = Math.max(1, Math.round(IN.riskUsd / (risk * IN.pointValue)));
  order.open = false;
  if (order.day !== curDay) { curDay = order.day; dayCount = 0; }
  dayCount++;
  markEntry(dir, entry);
};
// One bar of an open position; returns true if the trade closed in this bar.
var manage = function (k, fillBar) {
  var o = BO[k], h = BH[k], l = BL[k];
  if (BDAY[k] !== pos.day) { closeTrade(BC[k - 1], k - 1, 'day'); return true; }
  var ex = exitTdm();
  if (BTDMO[k] >= ex || (BTDMO[k] < ex && BTDMC[k] > ex)) { closeTrade(o, k, 'session'); return true; }
  var sameAsFill = fillBar && CFG.entry !== 'market';
  // On the bar a stop order fills, the bar's other extreme may have come before the fill.
  // Assume the usual path: a green bar goes open-low-high-close, a red bar open-high-low-close.
  var beforeFill = sameAsFill && (pos.dir > 0 ? BC[k] >= o : BC[k] <= o);
  if (!beforeFill) {
    if (pos.dir > 0 && l <= pos.stop) { closeTrade((sameAsFill || o > pos.stop) ? pos.stop : o, k, pos.trailing ? 'trail' : 'stop'); return true; }
    if (pos.dir < 0 && h >= pos.stop) { closeTrade((sameAsFill || o < pos.stop) ? pos.stop : o, k, pos.trailing ? 'trail' : 'stop'); return true; }
  }
  pos.best = pos.dir > 0 ? Math.max(pos.best, h) : Math.min(pos.best, l);
  if (!beforeFill && CFG.trail && (pos.best - pos.entry) * pos.dir >= pos.risk && ATR[k] > 0) {
    var ns = pos.best - pos.dir * 2 * ATR[k];
    if ((ns - pos.stop) * pos.dir > 0) { pos.stop = ns; pos.trailing = true; }
  }
  return false;
};

var onBar = function (k) {
  updateIndicators(k);
  var sg = setupAt(k);                              // always run: it also tracks gaps
  var goLong = sg.up && k >= CFG.warmup;
  var goShort = sg.dn && IN.shorts && k >= CFG.warmup;
  var evaluate = true;
  if (order.open) {
    if (order.kind === 'market') {
      order.open = false;
      if (BDAY[k] === order.day && BTDMO[k] < exitTdm()) {
        openTrade(k, BO[k]);
        if (!manage(k, true)) evaluate = false;
      }
    } else {
      if (order.alive && (BDAY[k] !== order.day || BTDMO[k] >= exitTdm())) order.alive = false;
      var hit = order.dir > 0 ? BH[k] >= order.px : BL[k] <= order.px;
      if (order.alive && hit) {
        var entry = order.dir > 0 ? Math.max(BO[k], order.px) : Math.min(BO[k], order.px);
        openTrade(k, entry);
        if (!manage(k, true)) evaluate = false;
      } else if (k >= order.until) {
        order.open = false;
      } else {
        evaluate = false;
      }
    }
  } else if (pos.open) {
    if (!manage(k, false)) evaluate = false;
  }
  if (!evaluate || pos.open || order.open) return;
  // a new setup on this bar's close
  if (goLong === goShort) return;
  var tc = BTDMC[k];
  if (tc < tdmOf(CFG.sesFrom) || tc > tdmOf(CFG.sesTo)) return;
  if (BDAY[k] === curDay && dayCount >= CFG.maxPerDay) return;
  if (!(ATR[k] > 0)) return;
  var dir = goLong ? 1 : -1;
  order.open = true; order.kind = CFG.entry; order.dir = dir; order.sig = k; order.day = BDAY[k]; order.atr = ATR[k];
  order.alive = true; order.until = k + 3;
  order.px = dir > 0 ? BH[k] + IN.tick : BL[k] - IN.tick;
  markSetup(dir, BC[k]);
};

// ------------------------------------------------------------------ bar feed
// Each bar is processed once, when the next bar appears, so only closed bars count.
onTick = (length, _moment, _, ta, inputs) => {
  try {
    readInputs(inputs);
    var t0 = time(0);
    if (t0 === undefined || t0 === null || isNaN(t0) || t0 === lastSeen) return;
    var first = lastSeen === -1;
    lastSeen = t0;
    if (first) return;
    var t1 = time(1);
    if (t1 === undefined || t1 === null || isNaN(t1)) return;
    var t = toMs(t1);
    var o = openC(1), h = high(1), l = low(1), c = closeC(1);
    if (isNaN(o) || isNaN(h) || isNaN(l) || isNaN(c)) return;
    if (BT.length && t < BT[BT.length - 1]) resetState();     // replay moved back in time: start over
    if (BT.length && t === BT[BT.length - 1]) return;
    var tdm = tradingMinute(t);
    BT.push(t); BO.push(o); BH.push(h); BL.push(l); BC.push(c);
    BDAY.push(tradingDay(t)); BTDMO.push(tdm); BTDMC.push(Math.min(tdm + CFG.tf, 1440));
    onBar(BT.length - 1);
  } catch (e) {
    showError(String(e));
  }
};
